version: '3.8'

services:
  frontend:
    container_name: despro-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - EXPO_PUBLIC_API_URL=https://mbg-be.mrt.qzz.io/api/v1/docs
    ports:
      - "8080:80"
    environment:
      - EXPO_PUBLIC_API_URL=https://mbg-be.mrt.qzz.io/api/v1/docs
    networks:
      - cloudflared-private
    restart: always

networks:
  cloudflared-private:
    external: true